//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_BudgeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class o_income
    {
        public int oinc_Id { get; set; }
        public string oinc_name { get; set; }
        public int uid { get; set; }
    
        public virtual user user { get; set; }
    }
}
