//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_BudgeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trasaction
    {
        public int tid { get; set; }
        public string tdate { get; set; }
        public string ttime { get; set; }
        public string t_cat { get; set; }
        public int tot_inc { get; set; }
        public int tot_exp { get; set; }
        public int uid { get; set; }
    
        public virtual user user { get; set; }
    }
}
